default: &default
  cloud_name: <%= ENV["CLOUDINARY_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default