
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &default
  adapter: postgresql
  encoding: unicode
  database: ngo_blog_development
  pool: 5
  username: "postgres"
  password: ""

production:
  <<: *default
  database: ngo_blog_production
  username: "postgres"
  password: ""

test:
  <<: *default
  database: ngo_blog_test
