development: &default
  adapter: postgresql
  encoding: unicode
  database: ngo_blog_development
  pool: 5
  username: "postgres"
  password: ""

production:
  <<: *default
  adapter: postgresql
  database: ngo_blog_production
  username: "postgres"



test:
  <<: *default
  database: ngo_blog_test
